In [ ]:
import numpy as np

: 

In [2]:
a = np.array([12,3,4,5,6,2])
a.shape

(6,)

In [3]:
b= a[np.newaxis,:]
c=a[:,None]
d=np.expand_dims(a,axis=1)
print(a)
print(b)
print(c)
print(d)
print(a)

[12  3  4  5  6  2]
[[12  3  4  5  6  2]]
[[12]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 2]]
[[12]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 2]]
[12  3  4  5  6  2]


In [4]:
b.shape

(1, 6)

In [5]:
a2= np.linspace(1,20,20)
b2 = a2.reshape(2,-1)
a2.shape=(4,-1)

In [46]:
d2= np.ones((2,3))

In [49]:
d2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
b2.base is a2.base

True

In [7]:
b2

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]])

In [8]:
print(a2)
c2 = np.flip(a2,axis=1)
print(c2)
c2 = np.flip(a2,axis=0)
print(c2)
c2 = np.flip(a2)
print(c2)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
[[ 5.  4.  3.  2.  1.]
 [10.  9.  8.  7.  6.]
 [15. 14. 13. 12. 11.]
 [20. 19. 18. 17. 16.]]
[[16. 17. 18. 19. 20.]
 [11. 12. 13. 14. 15.]
 [ 6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.]]
[[20. 19. 18. 17. 16.]
 [15. 14. 13. 12. 11.]
 [10.  9.  8.  7.  6.]
 [ 5.  4.  3.  2.  1.]]


In [9]:
c2.base is a2.base

True

In [10]:
a3 = np.linspace(0, 5, 5)
b3 = a3.ravel()
c3 = a3.flatten()

In [11]:
b3.base is a3.base

True

In [12]:
c3.base is a3.base

False

In [13]:
a3[1]=99
print( 
a3,b3,c3   
)

[ 0.   99.    2.5   3.75  5.  ] [ 0.   99.    2.5   3.75  5.  ] [0.   1.25 2.5  3.75 5.  ]


In [14]:
b3[2]=88
print( 
a3,b3,c3   
)

[ 0.   99.   88.    3.75  5.  ] [ 0.   99.   88.    3.75  5.  ] [0.   1.25 2.5  3.75 5.  ]


In [15]:
c3[3]=77
print( 
a3,b3,c3   
)

[ 0.   99.   88.    3.75  5.  ] [ 0.   99.   88.    3.75  5.  ] [ 0.    1.25  2.5  77.    5.  ]


In [16]:
np.save('array',a3)

In [17]:
a4= np.load('array.npy')

In [18]:
a4 == a3

array([ True,  True,  True,  True,  True])

In [28]:
a5 = np.arange(0,10,1)
a5[a5>5]

array([6, 7, 8, 9])

In [27]:
b5=a5>5
b5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [31]:
a2

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [35]:
sum=a2.sum(0)
print(sum)
sum2=a2.sum(1)
print(sum2)
sum3=a2.sum(-1)
print(sum3)

[34. 38. 42. 46. 50.]
[15. 40. 65. 90.]
[15. 40. 65. 90.]


In [41]:
a2[sum2 <= 40, :]

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [52]:
print(a2)
a2.base

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [63]:
a6 = np.array([[1, 2], [3, 4]])
b6=a6.view()
print(a6)
a6[1,1]=99
print(f' {a6} \n b6 matrix\n{b6}')
a6.base

[[1 2]
 [3 4]]
 [[ 1  2]
 [ 3 99]] 
 b6 matrix
[[ 1  2]
 [ 3 99]]


In [67]:
slice(0,2,) # == 0:2

slice(0, 2, None)

In [82]:
el = (Ellipsis,3)
el

(Ellipsis, 3)

In [79]:
a2

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [83]:
a2[el]

array([ 4.,  9., 14., 19.])

In [84]:
list1=[[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]]