In [1]:
import numpy as np

In [2]:
a = np.array([1, 1, 2])
b = np.ndarray(1, int)
c = np.array([[11.2, 1000, 3], [2, 4, 7],[1,22,3]])

In [3]:
print(f'a: {type(a)}')
print(f'b: {type(b)}')
print(f'c: {type(c)}')

a: <class 'numpy.ndarray'>
b: <class 'numpy.ndarray'>
c: <class 'numpy.ndarray'>


In [4]:
c.data

In [5]:
empty = np.empty((2,2))

In [6]:
type(empty)

numpy.ndarray

In [7]:
d=np.arange(12).reshape((4,3))
id(d)

140006825480432

In [8]:
d.reshape(6,2)
id(d)

140006825480432

In [9]:
d +=1
id(d)

140006825480432

In [10]:
e=d
d *=2
e

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [11]:
e[:,2]

array([ 6, 12, 18, 24])

In [12]:
b=np.array([12,3,4,55,6,7,4,6,6,7,8,9,1,2,34,3])
print(b)
b[:4:2]=1000
b

[12  3  4 55  6  7  4  6  6  7  8  9  1  2 34  3]


array([1000,    3, 1000,   55,    6,    7,    4,    6,    6,    7,    8,
          9,    1,    2,   34,    3])

In [13]:
c = np. array([[[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]])


In [14]:
c.shape=(1,6,2)

In [15]:
c

array([[[  0,   1],
        [  2,  10],
        [ 12,  13],
        [100, 101],
        [102, 110],
        [112, 113]]])

In [16]:
a_m = np.array(
    [
        [1,2,3,4,5,6],
        [11,12,13,14,15,16],
        [21,22,23,24,25,26]
    ] 
)

b_m = np.array(
    [
        [101,102,103,104,105,106],
        [111,112,113,114,115,116],
        [121,122,123,124,125,126]
    ]
)

c_v = np.array(
    [
        91,92,93
    ]
)

In [17]:
np.vstack((a_m,b_m))

array([[  1,   2,   3,   4,   5,   6],
       [ 11,  12,  13,  14,  15,  16],
       [ 21,  22,  23,  24,  25,  26],
       [101, 102, 103, 104, 105, 106],
       [111, 112, 113, 114, 115, 116],
       [121, 122, 123, 124, 125, 126]])

In [18]:
np.hstack((c_v,c_v)).ndim

1

In [19]:
a_m.ndim

2

In [20]:
dtest_m = np.array(
    [
        [1],
        [3],
        [4]
    ]
) 

In [21]:
np.hstack((a_m,dtest_m))

array([[ 1,  2,  3,  4,  5,  6,  1],
       [11, 12, 13, 14, 15, 16,  3],
       [21, 22, 23, 24, 25, 26,  4]])

In [22]:
c_q = np.array(
    [
        [
            [0, 1, 2], 
            [10, 12, 13]
        ], 
        [
            [100, 101, 102], 
            [110, 112, 113]
        ],
        [
            [200, 201, 202], 
            [210, 212, 213]
        ]
        ]
    )

In [23]:
print(c_q.shape)
print(a_m.shape)

(3, 2, 3)
(3, 6)


In [24]:
c_q[0]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [25]:
c_q


array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]],

       [[200, 201, 202],
        [210, 212, 213]]])

In [26]:
c_q.T

array([[[  0, 100, 200],
        [ 10, 110, 210]],

       [[  1, 101, 201],
        [ 12, 112, 212]],

       [[  2, 102, 202],
        [ 13, 113, 213]]])

In [27]:
a_m.T

array([[ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26]])

In [28]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print('a')
print(a)
print('b')
print(b)

print('0')
print(np.concatenate((a, b), axis=0))
print('1')
print(np.concatenate((a, b.T), axis=1))
print('none')
print(np.concatenate((a, b), axis=None))

a
[[1 2]
 [3 4]]
b
[[5 6]]
0
[[1 2]
 [3 4]
 [5 6]]
1
[[1 2 5]
 [3 4 6]]
none
[1 2 3 4 5 6]


In [29]:
mask_v=np.ma.array([1,2,3,4,5])

In [30]:
mask_v[1]=np.ma.masked

In [31]:
mask_v

masked_array(data=[1, --, 3, 4, 5],
             mask=[False,  True, False, False, False],
       fill_value=999999)

In [32]:
a_m

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26]])

In [33]:
np.hsplit(a_m,3)

[array([[ 1,  2],
        [11, 12],
        [21, 22]]),
 array([[ 3,  4],
        [13, 14],
        [23, 24]]),
 array([[ 5,  6],
        [15, 16],
        [25, 26]])]

In [34]:
np.array_split(a_m,3,0)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[11, 12, 13, 14, 15, 16]]),
 array([[21, 22, 23, 24, 25, 26]])]

In [35]:
a2_m= a_m.view()
a3_m = a_m.reshape(2,-1)
a2_m.shape=(2,-1)

In [36]:
a_m

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26]])

In [37]:
a2_m

array([[ 1,  2,  3,  4,  5,  6, 11, 12, 13],
       [14, 15, 16, 21, 22, 23, 24, 25, 26]])

In [38]:
a3_m

array([[ 1,  2,  3,  4,  5,  6, 11, 12, 13],
       [14, 15, 16, 21, 22, 23, 24, 25, 26]])

In [39]:
print(a_m is a2_m.base)
print(a_m is a3_m.base)
print(a2_m is a3_m.base)

True
True
False


In [40]:
print(id(a_m))
print(id(a2_m))
print(id(a3_m))

140006825483600
140006825527024
140006825528176


In [41]:
a2_m[1,2]=9999
a2_m

array([[   1,    2,    3,    4,    5,    6,   11,   12,   13],
       [  14,   15, 9999,   21,   22,   23,   24,   25,   26]])

In [42]:
a_m

array([[   1,    2,    3,    4,    5,    6],
       [  11,   12,   13,   14,   15, 9999],
       [  21,   22,   23,   24,   25,   26]])

In [43]:
a4_m=a_m.copy()

In [44]:
a4_m[0,3]=777
a_m[0,4]=8888

In [45]:
a_m

array([[   1,    2,    3,    4, 8888,    6],
       [  11,   12,   13,   14,   15, 9999],
       [  21,   22,   23,   24,   25,   26]])

In [46]:
a4_m

array([[   1,    2,    3,  777,    5,    6],
       [  11,   12,   13,   14,   15, 9999],
       [  21,   22,   23,   24,   25,   26]])

In [47]:
a_m

array([[   1,    2,    3,    4, 8888,    6],
       [  11,   12,   13,   14,   15, 9999],
       [  21,   22,   23,   24,   25,   26]])

In [48]:
a_m.argmax(axis=1)

array([4, 5, 5])

In [49]:
print(c_v)
c_v[[0,0,2]]+=1
print(c_v)

[91 92 93]
[92 92 94]


In [50]:
a = np.arange(12).reshape(3, 4)
b = a > 4
print(b)
a[b]

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


array([ 5,  6,  7,  8,  9, 10, 11])