In [1]:
import numpy as np

In [38]:
def err(f):
    def dec(*args):
        try:
            a = f(args)
        except: print('error')
        else: 
            print('OK')
            return a
        finally: print('Finale')
        
    return dec
    

In [3]:
a_m = np.array(
    [[ 0.0,  1.0,  2.0],
    [10.0, 11.0, 12.0],
    [20.0, 21.0, 22.0],
    [30.0, 31.0, 32.0]]
    )
b_v = np.array([1.0, 2.0, 3.0])
print(b_v)
c_m = b_v.copy()
c_m=c_m[None,:]
print(c_m)
d_m = b_v.copy()
d_m = d_m[:,None]
print(d_m)

[1. 2. 3.]
[[1. 2. 3.]]
[[1.]
 [2.]
 [3.]]


In [4]:
a_m+b_v

array([[ 1.,  3.,  5.],
       [11., 13., 15.],
       [21., 23., 25.],
       [31., 33., 35.]])

In [5]:
a_m+c_m

array([[ 1.,  3.,  5.],
       [11., 13., 15.],
       [21., 23., 25.],
       [31., 33., 35.]])

In [6]:

try:
    print(a_m+ d_m)
except: print('error')
else: print('OK')
finally: print('Finale')

error
Finale


In [8]:
pr=err(print)

In [12]:
pr(102)

(102,) {}
OK
Finale


In [43]:
try:
    print(c_m@c_m)
except: print('error')
else: print('OK')
finally: print('Try another path')


error
Try another path


In [78]:
class Infix:
    def __init__(self, function):
        self.function = function
    def __ror__(self, other):
        return Infix(lambda x, self=self, other=other: self.function(other, x))
    def __or__(self, other):
        return self.function(other)
    # def __rlshift__(self, other):
    #     return Infix(lambda x, self=self, other=other: self.function(other, x))
    # def __rshift__(self, other):
    #     return self.function(other)
    def __call__(self, value1, value2):
        return self.function(value1, value2)

In [79]:
x = Infix( lambda x,y: x**y)

In [80]:
2   |x|   10

1024